# ComfyUI Commander Manifest
# Use this to define your "Scenes" (Workflows groups)

workflows_repo: "https://github.com/zachyuan/sync_docker.git"

# Define different scenes to optimize startup time
# Each scene downloads only what it needs
scenes:
  flux_dev:
    # Nodes to SYMLINK from /opt/nodes_pool/
    # If not in pool, will be git cloned automatically
    nodes:
      # - "https://github.com/ltdrdata/ComfyUI-Impact-Pack.git"
      # - "https://github.com/city96/ComfyUI-GGUF.git"
    
    # Models to download via aria2c
    models:
      # - url: "https://huggingface.co/city96/FLUX.1-dev-gguf/resolve/main/flux1-dev-Q8_0.gguf"
        # path: "models/unet"
        # name: "flux1-dev-Q8_0.gguf"
      - url: "https://huggingface.co/comfyanonymous/wd-1.5-beta2_unCLIP/resolve/main/wd-1-5-beta2-unclip-h-fp16.safetensors"
        path: "models/clip"
        name: "wd-1-5-beta2-unclip-h-fp16.safetensors"

  portrait_photography:
    nodes:
      - "ComfyUI-PhotoMaker"
      - "https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker-ZHO.git"
    models:
      - url: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors"
        path: "models/checkpoints"
        name: "sd_xl_base_1.0.safetensors"

  versatile-sd:
    nodes:
      - url: "https://github.com/yolain/ComfyUI-Easy-Use.git"
        version: "v1.3.6" # comfyui-easy-use
      - "https://github.com/ronniebasak/ComfyUI-Tara-LLM-Integration.git" # comfyui-tara-llm-integration
      - "https://github.com/Fannovel16/comfyui_controlnet_aux.git" # comfyui_controlnet_aux
      - "https://github.com/cubiq/ComfyUI_IPAdapter_plus.git" # comfyui_ipadapter_plus
      - "https://github.com/huchenlei/ComfyUI-IC-Light.git" # huchenlei/ComfyUI-IC-Light
    models:
    - url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors"
      path: "models/clip_vision"
      name: "CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors"
    - url: "https://huggingface.co/Lykon/dreamshaper-xl-lightning/resolve/main/DreamShaperXL_Lightning.safetensors?download=true"
      path: "models/checkpoints"
      name: "DreamShaperXL_Lightning.safetensors"
    - url: "https://huggingface.co/Lykon/DreamShaper/resolve/main/DreamShaper_8_pruned.safetensors?download=true"
      path: "models/checkpoints"
      name: "DreamShaper_8_pruned.safetensors"
    - url: "https://civitai.com/api/download/models/135867?type=Model&format=SafeTensor"
      path: "models/loras"
      name: "add-detail-xl.safetensors"
    - url: "https://civitai.com/api/download/models/450187"
      path: "models/checkpoints"
      name: "dreamshaperXL_lightningInpaint.safetensors"
    - url: "https://huggingface.co/huchenlei/IC-Light-ldm/resolve/main/iclight_sd15_fbc_unet_ldm.safetensors?download=true"
      path: "models/unet"
      name: "iclight_sd15_fbc_unet_ldm.safetensors"
    - url: "https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/ip-adapter_sdxl.safetensors"
      path: "models/ipadapter"
      name: "ip-adapter_sdxl.safetensors"
    - url: "https://huggingface.co/TheMistoAI/MistoLine/resolve/main/mistoLine_rank256.safetensors?download=true"
      path: "models/controlnet"
      name: "mistoLine_rank256.safetensors"

  BiRefNet:
    nodes:
      - https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes
      - https://github.com/TTPlanetPig/Comfyui_Object_Migration
      - https://github.com/aining2022/ComfyUI_Swwan
      - https://github.com/chflame163/ComfyUI_LayerStyle_Advance
      - https://github.com/cubiq/ComfyUI_essentials
      - https://github.com/ltdrdata/was-node-suite-comfyui
      - https://github.com/rgthree/rgthree-comfy
      - https://github.com/yolain/ComfyUI-Easy-Use
      - https://github.com/kijai/ComfyUI-KJNodes
    models:
      - url: "https://huggingface.co/yiwangsimple/BiRefNet-general-epoch_244/resolve/main/BiRefNet-general-epoch_244.pth"
        path: "models/BiRefNet/pth" 
        name: "BiRefNet-general-epoch_244.pth"
      - url: "https://huggingface.co/yuvraj108c/RMBG-2.0/resolve/main/pytorch_model.bin"
        path: "models/RMBG" 
        name: "RMBG_2.0.bin"
  
  Layered_cutout:
    nodes:
      - "https://github.com/jamesWalker55/comfyui-various"
      - "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
      - "https://github.com/aining2022/ComfyUI_Swwan"
      - "https://github.com/pythongosssss/ComfyUI-Custom-Scripts"
      - "https://github.com/M1kep/ComfyLiterals"
      - "https://github.com/YaserJaradeh/comfyui-yaser-nodes"
      - "https://github.com/olduvai-jp/ComfyUI-S3-IO"
    models:
      - url: https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
        path: models/text_encoders/qwen
        name: qwen_2.5_vl_7b_fp8_scaled.safetensors
      - url: https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/main/ae.safetensors
        path: models/vae
        name: qwen_image_layered_vae.safetensors
        
      


  

# Global settings
global:

  # Shared nodes for ALL scenes
  nodes:
    - "https://github.com/Comfy-Org/ComfyUI-Manager.git" 
    # - "https://github.com/ltdrdata/ComfyUI-Impact-Pack.git" 
    # - "https://github.com/Fannovel16/comfyui_controlnet_aux.git"
    - "https://github.com/rgthree/rgthree-comfy.git" 
    - "https://github.com/cubiq/ComfyUI_essentials.git" 
    # - "https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git" 
    - "https://github.com/crystian/ComfyUI-Crystools.git" 
    # - "https://github.com/yolain/ComfyUI-Easy-Use.git" 
    # - "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git" 
    # - "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes.git"

  # Shared models for ALL scenes
  models:
    - url: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors"
      path: "models/checkpoints"
      name: "v1-5-pruned-emaonly.safetensors"
